= Using SVN and Git to initiate a PDF build

This doc describes how to use git+svn to interoperate between git and our SVN repo.  It also describes how to initiate a buld from git and retrieve the built files.

== Install git+svn

If you don't have it already, you'll need to install git+svn.  Here's the command in Ubuntu:

----
sudo apt-get install git-svn
----

== Get the most recent revision number from the SVN repo

The basic process is to create the directory that you want to use git+svn in, checkout the svn repo and determine the correct revision number, use git+svn to initialize the git repo, and then delete the safari repo.  Here's an example for how to set up the a git+svn "javascript" repo for the SVN repo https://prod.oreilly.com/external/authors/books/9781449311889/current/.

----
mkdir javascript
cd javascript
svn checkout --username "odewahn@oreilly.com" "https://prod.oreilly.com/external/authors/books/9781449311889/current/" 
cd current
svn log
----

This will produce a log file where you can get a bunch of revision numbers with the most recent revisions starting at the top, like this:

----
macodewahn:current odewahn$ svn log
r349256 | dcps@oreilly.com | 2011-07-06 11:16:06 -0400 (Wed, 06 Jul 2011) | 1 line
...
----

Make a note of this revision, which in the example is "349256." Next, delete the current directory that the previous steps created:

----
rm -rf current
----

== Initialize a new "git svn" repo

Next, initialize the new git repo:

----
cd ..
git svn init --username "odewahn@oreilly.com" "https://prod.oreilly.com/external/authors/books/9781449311827/current/"
git svn fetch -r 349256
git rebase --onto remotes/git-svn --root master
----

== Do your stuff in git

Congrats, you're now using git.  You can add files, edit, and commit like you normally do.  The one ting to consider: be careful when you're using git's branching facilities.  git branches should only be on your local machine. As long as you don't push any of those with git svn you should be able to do all the normal git branch and merge stuff locally with svn even knowing about it.

Other than that, go to!

== Commit to SVN and generate a PDF

Use this command when you're ready to save your files to the SVN repo:

----
git svn dcommit
----


== Generate a PDF 

If you want to also trigger a pdf build a PDF, just add the "orm:asciidoc" string in your commit message and then dcommit, like this:

----
git commit -a -m"orm:asciidoc"
git svn dcommit
----

This initiates the PDF build process through a set of SVN hooks.  After a few minutes, you can retrieve the pdf with these 2 commands:

----
git svn rebase
git svn fetch
----
